### PR TITLE
Limit SlackBuilds indexing depth

### PR DESCRIPTION
**Pull request by atelszewski**
Limit SlackBuilds indexing depth to `category/prgnam/prgnam.SlackBuild`.

It this way, it's possible to store original SlackBuild for reference together with the new SlackBuild version.

For example, I have a `slackup/git/git.SlackBuild`, that is based on the SlackBuild from stock Slackware. For reference, I store this stock SlackBuild in `slackup/git/git.SlackBuild.orig/git.SlackBuild`.

Without this change, `slackup/git/git.SlackBuild.orig/git.SlackBuild` is indexed and `slackrepo` tries to build it.

### CODE REVIEW

**Comment by aclemons** [comment]
slackrepo works with more than just SBo, so I would not want to prescribe what the directory structure should look like. Can we make this a configuration option instead? Then you could set a max depth the .conf file for your repo?

**Comment by atelszewski** [comment]
Hi,

> Can we make this a configuration option instead?

Sure! :-)

Will you make the change or should I look how to do it?

On a side note:

my change didn't work until I have manually removed the indexed SlackBuild from `slackbuilds` table in the database.
What I mean is that, I ran `slackrepo`, it indexed `slackup/git/git.SlackBuild.orig/git.SlackBuild` and then, even with the change, `slackrepo` was still trying to build `slackup/git/git.SlackBuild.orig/git.SlackBuild`. It only stopped trying to build it once I _manually_ removed it from `slackbuilds` table.

It's strange, because `db_index_slackbuilds()` drops the `slackbuilds` table each time `slackrepo` is run, no?

Please let me know if I should create a separate bug ticket for the above.

Thank you for your support! :-)

--
Best regards,
Andrzej Telszewski

**Comment by aclemons** [comment]
> Will you make the change or should I look how to do it?

I am not planning to. Please send a PR for review and we can see about getting it merged.

**Comment by aclemons** [comment]
Regarding the indexing, please open an issue for me so I do not forget to investigate and follow up. Thank you

**Comment by atelszewski** [comment]
> I am not planning to. Please send a PR for review and we can see about getting it merged.

Ok, I won't do it neither in the close future and will keep the change in my fork.
Maybe if there's bigger need, we can come back to it.

> Regarding the indexing, please open an issue for me so I do not forget to investigate and follow up. Thank you

Will do! :-)

--
Best regards,
Andrzej Telszewski

**Comment by atelszewski** [comment]
@aclemons I won't report an issue related to the indexing.

I found out that running indexing depends on the git status of the repository,
and I can't remember what was the status of the repo at the time I encountered the issue.
If I recall correctly, there were no changes to the repo and that would be the reason the indexer didn't run.

--
Best regards,
Andrzej Telszewski

**Pull request closed without merging**
